version: "3"

services:
    influxdb:
        image: influxdb
        container_name: influxdb
        ports: 
            - "8083:8083"
            - "8086:8086"
        volumes: 
            - ./influxdb:/var/lib/influxdb
        networks: 
            - "iotstack"

    mosquitto:
        image: eclipse-mosquitto
        container_name: mosquitto
        volumes: 
            - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./mosquitto/log:/mosquitto/log
            - ./mosquitto/data:/mosquitto/data
        ports:
            - "1883:1883"
        links: 
            - telegraf
        restart: always
        networks: 
            - "iotstack"
    
    telegraf:
        image: telegraf:1.13
        container_name: telegraf
        links: 
            - influxdb
        volumes: 
            - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
        networks: 
            - "iotstack"
    
    grafana:
        image: grafana/grafana
        container_name: grafana
        ports: 
            - "3000:3000"
        user: "0"
        links: 
            - influxdb
        volumes: 
            - ./grafana/data:/var/lib/grafana
        networks: 
            - "iotstack"

volumes: 
    influxdb:
    grafana:

networks: 
    iotstack:
